---
- name: Require password for deploy sudo
  hosts: all
  become: true
  vars:
    deploy_password_hash: "$6$ltlCfXO/k0XMb1RX$pLQo411M/ljTaj4oCyHGebILAO.h.ZJnH//uCTK3HAXJqGOXQAN0A9Q6TPuLbhK/F0/9HhM8kqiwVd0dTpcj1."

  tasks:
    - name: Set password for deploy user
      ansible.builtin.user:
        name: deploy
        password: "{{ deploy_password_hash }}"

    - name: Ensure deploy uses passworded sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/deploy
        regexp: '^deploy'
        line: 'deploy ALL=(ALL) ALL'
        create: true
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
