---
- hosts: db
  become: true
  vars_files:
    - vault.yaml
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Reload MariaDB-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: download python3-PyMySQL
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present
    
    - name: create a database
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: make a user
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ webappuser_password }}"
        host: "%"
        priv: "webappdb.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: true
