---
- hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Reload MariaDB-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

