---
- name: Configure HTTPS web server
  hosts: web
  become: true
  vars:
    ip_address: "192.168.121.105"

  tasks:
    - name: Ensure web root directory exists
      ansible.builtin.file:
        path: /var/www/example.internal/html
        state: directory
        owner: root
        group: root
        mode: '0755'
      register: dir_res

    - name: Print the value of dir_res
      ansible.builtin.debug:
        var: dir_res
      when: dir_res is changed

    - name: Deploy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/example.internal/html/index.html
        owner: root
        group: root
        mode: '0644'
      register: html_res

    - name: Print the value of html_res
      ansible.builtin.debug:
        var: html_res
      when: html_res is changed

    - name: Copy HTTPS configuration
      ansible.builtin.copy:
        src: https.conf
        dest: /etc/nginx/conf.d/https.conf
        owner: root
        group: root
        mode: '0644'
      register: https_res

    - name: Print the value of https_res
      ansible.builtin.debug:
        var: https_res
      when: https_res is changed

    - name: Deploy nginx configuration from template
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: root
        group: root
        mode: '0644'
      register: nginx_res


    - name: Print the value of nginx_res
      ansible.builtin.debug:
        var: nginx_res
      when: nginx_res is changed

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
