---

  - name: Ensure nginx is installed
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Ensure the /etc/pki/nginx directory exists
    ansible.builtin.file:
      path: /etc/pki/nginx
      state: directory
      mode: "0755"
      owner: root

  - name: Ensure we have a /etc/pkig/nginx/private directory
    ansible.builtin.file:
      path: /etc/pki/nginx/private
      state: directory
      mode: "0700"
      owner: root

  - name: Ensure we have necessary software installed
    ansible.builtin.package:
      name: python3-cryptography
      state: present

  - name: Ensure we have a private key for our certificate
    community.crypto.openssl_privatekey:
      path: /etc/pki/nginx/private/server.key

  - name: Create a self-signed certificate
    community.crypto.x509_certificate:
      path: /etc/pki/nginx/server.crt
      privatekey_path: /etc/pki/nginx/private/server.key
      provider: selfsigned




  - name: Ensure nginx is enabled and running
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Ensure web root directory exists
    ansible.builtin.file:
      path: /var/www/example.internal/html
      state: directory
      owner: root
      group: root
      mode: '0755'
    register: dir_res

  - name: Print the value of dir_res
    ansible.builtin.debug:
      var: dir_res
    when: dir_res is changed

  - name: Deploy index.html
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/example.internal/html/index.html
      owner: root
      group: root
      mode: '0644'
    register: html_res

  - name: Copy HTTPS configuration
    ansible.builtin.copy:
      src: files/https.conf
      dest: /etc/nginx/conf.d/https.conf
      owner: root
      group: root
      mode: '0644'
    register: https_res
    notify: Reload nginx

  - name: Print the value of html_res
    ansible.builtin.debug:
      var: html_res
    when: html_res is changed

  - name: Ensure nginx conf.d directory exists
    ansible.builtin.file:
      path: /etc/nginx/conf.d
      state: directory
      owner: root
      group: root
      mode: '0755'

    register: https_res
    notify: Reload nginx


  - name: Print the value of https_res
    ansible.builtin.debug:
      var: https_res
    when: https_res is changed


  - name: Deploy nginx configuration from template
    ansible.builtin.template:
      src: templates/example.internal.conf.j2
      dest: /etc/nginx/conf.d/example.internal.conf
      owner: root
      group: root
      mode: '0644'
    register: nginx_res
    notify: Reload nginx

  - name: Print the value of nginx_res
    ansible.builtin.debug:
      var: nginx_res
    when: nginx_res is changed


  - name: Ensure nginx key directory exists
    ansible.builtin.file:
      path: /etc/pki/nginx/private
      state: directory
      owner: root
      group: root
      mode: '0750'

  - name: Ensure nginx key file has correct permissions
    ansible.builtin.file:
      path: /etc/pki/nginx/private/server.key
      owner: root
      group: nginx
      mode: '0640'

